nanotech-empa/aiida-nanotech-empa

- aiida_nanotech_empa/utils.py
A bug to the cube file parser has been introduced in the PR #8.
The PR fixes the bug.
> Fix cube file parser.

- aiida_nanotech_empa/workflows/nanoribbon.py
Previosly, all the export orbital steps were run in one work chain
step which caused all of them to be executed in parallel. To make
sure that those calculations are actually run sequentially we
reshape the workflow and run one export calcjob per step.
> Execute every orbitals export job in a separate work chain step.

- aiida_nanotech_empa/workflows/nanoribbon.py
some users may have a maximum number of nodes on which they are allowed to run
> added max allowed # nodes and memory per node

- aiida_nanotech_empa/workflows/nanoribbon.py
Now if a step fails the workchian stos and finish with exit code 300
> added exit codes to intermediate steps of the workchain

- aiida_nanotech_empa/schedulers/lsf_ethz_euler.py
I the previous PR, I added the plugin for ETHZ Euler LSF scheduler, but somehow my testing didn't detect that it was super broken. Here's the fixed version.
> LSF plugin fix

- examples/workflows/example_cp2k_gw.py
- examples/workflows/example_cp2k_molopt.py
- setup.json
Changed the cp2k entry point names to match gaussian.
> cp2k entry point name change

- aiida_nanotech_empa/workflows/cp2k/molecule_gw_workchain.py
- aiida_nanotech_empa/workflows/cp2k/protocols/gw_protocols.yml
Now tries multiple different SCF sections in case of non-convergence or negative gap.
> Overhaul of GW workflow

- .github/check_version.py
- aiida_nanotech_empa/parsers/cubegen_pymol_parser.py
- aiida_nanotech_empa/utils/analyze_structure.py
- aiida_nanotech_empa/utils/common_utils.py
- aiida_nanotech_empa/utils/gaussian_wcs_postprocess.py
- aiida_nanotech_empa/utils/pymol_render.py
- aiida_nanotech_empa/workflows/cp2k/bulk_opt_workchain.py
- aiida_nanotech_empa/workflows/cp2k/cp2k_utils.py
- aiida_nanotech_empa/workflows/cp2k/molecule_gw_workchain.py
- aiida_nanotech_empa/workflows/cp2k/molecule_opt_workchain.py
- aiida_nanotech_empa/workflows/cp2k/slab_opt_workchain.py
- aiida_nanotech_empa/workflows/gaussian/delta_scf_workchain.py
- aiida_nanotech_empa/workflows/gaussian/spin_workchain.py
- aiida_nanotech_empa/workflows/qe/nanoribbon.py
- conftest.py
- examples/workflows/example_nanoribbon.py
- setup.json
- setup.py
allow to skip cell optimization in the workchain
> No geo opt

- aiida_nanotech_empa/utils/igor.py
- aiida_nanotech_empa/utils/stm_tools.py
Utilities to perform stm analysis on the output of the gaussian workchain, from the retrieved cube planes. Igor file support included, the STM images can be saved in .itx format.
To test if and how the usage works, the attached notebook can be used. Possibly it should be incorporated as an example calculation.
[stm.zip](https://github.com/nanotech-empa/aiida-nanotech-empa/files/7885163/stm.zip)
> gaussian stm tools & igor utilities

- aiida_nanotech_empa/utils/pymol_render.py
Seems that sometimes pymol doesn't create the image, even after the 100 sec wait. If this happens, call the pymol render command again.
Worked for my simple tests, but i didn't have access to the difficult case, which failed before.
@cpignedoli test the triangulene with this fix.
> pymol render try second time if failure

- setup.json
For more details see: https://github.com/nanotech-empa/aiida-gaussian/pull/10
> Set lower limit for aiida-gaussian to avoid issues.

- aiida_nanotech_empa/utils/stm_tools.py
Use `plt.*` methods instead of `ax.*`
> Update plot_mapping function.

- aiida_nanotech_empa/workflows/cp2k/protocols/gw_protocols.yml
Added memory_cut 1 in low scaling GW for GW-IC to avoid crashing
> Gw memory cut

- aiida_nanotech_empa/workflows/cp2k/fragment_separation.py
fixes #93 
- Always set charges, even if UKS is not specified.
- Kinds determination code is slightly better placed.
> Several changes in the FragmentSeparationWorkchain

- .github/workflows/ci.yml
> Fix CI that fail due to the absence of PGSQL-12

- aiida_nanotech_empa/workflows/cp2k/cp2k_utils.py
- aiida_nanotech_empa/workflows/cp2k/replica_workchain.py
Fixed a bug with walltime and added the torsion CV
> Implement torsion collective variable, fix a bug with a wall time.

- aiida_nanotech_empa/workflows/cp2k/replica_workchain.py
> use absolute value for convergence wrt CV increment

- aiida_nanotech_empa/workflows/cp2k/cp2k_utils.py
> Improve the compatibility check of available WFN for the UKS case

- aiida_nanotech_empa/plugins/hrstm.py
- aiida_nanotech_empa/plugins/overlap.py
- aiida_nanotech_empa/plugins/stm.py
- pyproject.toml
> Remove temporary fix for the `withmpi` problem

- aiida_nanotech_empa/workflows/cp2k/cp2k_utils.py
In constarints, the units for FIX_POINTS are by default bohr.
Added the [angstrom] key to be compatible with the GUI
> fixed units in FIXED_POINT in colvars

- aiida_nanotech_empa/workflows/cp2k/orbitals_workchain.py
- aiida_nanotech_empa/workflows/cp2k/pdos_workchain.py
- aiida_nanotech_empa/workflows/cp2k/stm_workchain.py
reduces number of nodes / system size according to alps
Tested on ALPS
> resources updated for alps

- aiida_nanotech_empa/workflows/qe/nanoribbon.py
Increased to 3600 the default walltime and set to 1800 teh walltime for exporting Hartree potential
> changed few defaults
